// 本文件由 tools/build.py 自动生成（切片 kaiyuan），请勿手工编辑。
// 加载后把本切片 bundle 挂到 window.SANDBOX_SLICES["kaiyuan"]。
(window.SANDBOX_SLICES = window.SANDBOX_SLICES || {});
window.SANDBOX_SLICES["kaiyuan"] = {
 "meta": {
  "kind": "county",
  "region": "liaobei",
  "title": "开原",
  "dossier_label": "开原",
  "subtitle": "辽北第一重镇 · 明卫所—清州县 · 万历末陷落",
  "primary_place": "kaiyuan_cheng",
  "dossier_event": "event:kaifa",
  "back": "枢纽",
  "lead": "开原是辽北第一重镇：明三万卫—清开原县，万历四十七年（1619）陷于后金，叶赫随之灭亡。下方为建置沿革与关键战事，点时间轴或左栏跳转。",
  "parties_note": "开原陷落（1619）在明、清、朝鲜三方叙事中各有侧重。系统不裁决，只并列。",
  "route_assertions": [
   "K008",
   "K009",
   "K020",
   "K027e"
  ],
  "subject_names": {
   "army:jin_kaifa": "后金攻开原兵力",
   "event:kaifa": "开铁之战",
   "place:kaiyuan_cheng": "开原城",
   "person:zhengzhifan": "郑之范",
   "event:yehe": "叶赫",
   "doc:kaiyuan_tushuo": "开原图说"
  },
  "page": "county.html?scene=kaiyuan",
  "key": "kaiyuan",
  "scene_id": "kaiyuan",
  "vocab_pack": "ming_qing",
  "terrain_grid": "liaodong"
 },
 "sources": [
  {
   "id": "kaiyuan_tushuo",
   "title": "开原图说",
   "party": "明·开原兵备道",
   "distance_label": "成书 1603，距开原陷落 16 年的实地踏勘",
   "stance_label": "本朝地方官修·当代",
   "compiler": "冯瑗（1572–1627）辑，万历末年成书",
   "color": "#7A5C2E",
   "period": "明万历",
   "stance": "official_local_contemporary"
  },
  {
   "id": "mingshi",
   "title": "明史",
   "party": "清修·明臣",
   "distance_label": "成书 1739，距事件约 120 年",
   "stance_label": "后朝官修",
   "compiler": "张廷玉等，《明史·地理志/列传》",
   "color": "#8C6239",
   "period": "清乾隆",
   "stance": "official_later_dynasty"
  },
  {
   "id": "ming_shenzong_shilu",
   "title": "明神宗实录",
   "party": "明廷官方",
   "distance_label": "成书约 1630，距万历末事约 10 年",
   "stance_label": "本朝官修·当代",
   "compiler": "明代历朝实录馆",
   "color": "#9C7A45",
   "period": "明",
   "stance": "official_contemporary"
  },
  {
   "id": "qing_taizu_shilu",
   "title": "清太祖实录",
   "party": "清修官史",
   "distance_label": "初纂 1636 后屡经改窜，距事件 17 年以上",
   "stance_label": "敌方官修",
   "compiler": "清代国史馆",
   "color": "#3D6B4F",
   "period": "清",
   "stance": "official_enemy"
  },
  {
   "id": "chaoxian_shilu",
   "title": "朝鲜李朝实录",
   "party": "朝鲜官方",
   "distance_label": "当代记注，事发当年即录",
   "stance_label": "第三方官修·逐日记注",
   "compiler": "朝鲜春秋馆",
   "color": "#2E7D8F",
   "period": "朝鲜",
   "stance": "third_party_official"
  },
  {
   "id": "xuantong_kao",
   "title": "开原县志·万历四十六年东夷入犯",
   "party": "清·地方志",
   "distance_label": "清末纂修，距明末事约 290 年",
   "stance_label": "地方志",
   "compiler": "《开原县志》（据《开原图说》转引）",
   "color": "#6E6A5E",
   "period": "清",
   "stance": "local_gazetteer"
  },
  {
   "id": "modern",
   "title": "现代考订",
   "party": "学界",
   "distance_label": "距事件 300 年以上，综合诸家",
   "stance_label": "学界考证",
   "compiler": "辽东镇长城与明清东北史综合研究",
   "color": "#2E7D8F",
   "period": "今",
   "stance": "scholarship"
  },
  {
   "id": "wiki",
   "title": "地方综述·维基/民族报",
   "party": "二手综述",
   "distance_label": "当代，未经同行评议；任何依赖它的断言都是待升级项",
   "stance_label": "三手综述",
   "compiler": "维基百科、中国民族报等公开综述",
   "color": "#8A8275",
   "period": "今",
   "stance": "tertiary"
  }
 ],
 "places": [
  {
   "id": "kaiyuan_cheng",
   "name": "开原城",
   "lon": 124.04,
   "lat": 42.54,
   "type": "capital",
   "modern": "今辽宁开原市老城街道",
   "note": "元开元路治，明三万卫/开原卫治，辽东北端第一重镇",
   "_global_id": "kaiyuan_cheng",
   "_other_scenes": [
    "liaoyang",
    "tieling"
   ],
   "elev": 88
  },
  {
   "id": "sanwan_wei",
   "name": "三万卫",
   "lon": 124.05,
   "lat": 42.55,
   "type": "wei",
   "modern": "开原城内",
   "note": "洪武二十一年（1388）徙治开元城，辽北军政核心",
   "elev": 89
  },
  {
   "id": "liaohai_wei",
   "name": "辽海卫",
   "lon": 124.02,
   "lat": 42.55,
   "type": "wei",
   "modern": "开原北城",
   "note": "洪武二十六年（1393）迁开原北城",
   "elev": 78
  },
  {
   "id": "anle_zhou",
   "name": "安乐州",
   "lon": 124.03,
   "lat": 42.53,
   "type": "zhou",
   "modern": "开原城内",
   "note": "永乐七年（1409）置，安置内附女真等族，辽东仅有的二州之一",
   "elev": 88
  },
  {
   "id": "guangshun",
   "name": "广顺关",
   "lon": 124.62,
   "lat": 42.42,
   "type": "guan",
   "modern": "开原东南（南关）",
   "note": "女真马市·南关市，通哈达、建州，开原东陆路",
   "elev": 196
  },
  {
   "id": "zhenbei",
   "name": "镇北关",
   "lon": 124.52,
   "lat": 42.78,
   "type": "guan",
   "modern": "开原东北（北关）",
   "note": "女真马市·北关市，通叶赫/海西，开原北陆路",
   "elev": 247
  },
  {
   "id": "xinan",
   "name": "新安关",
   "lon": 123.62,
   "lat": 42.55,
   "type": "guan",
   "modern": "开原西（鞑靼马市）",
   "note": "蒙古马市，开原西陆路",
   "elev": 96
  },
  {
   "id": "kaiyuan_mashi",
   "name": "开原马市",
   "lon": 124.06,
   "lat": 42.52,
   "type": "mashi",
   "modern": "开原城南门外",
   "note": "提督马市公署驻此，辽东贸易中心；三关三市，后扩四关四市",
   "elev": 95
  },
  {
   "id": "tieling",
   "name": "铁岭城",
   "lon": 123.83,
   "lat": 42.29,
   "type": "city",
   "modern": "今辽宁铁岭市",
   "note": "开原重要卫城，万历四十七年七月继开原后陷落",
   "_global_id": "tieling",
   "_other_scenes": [
    "liaoyang",
    "tieling"
   ],
   "elev": 71
  },
  {
   "id": "liaoyang",
   "name": "辽阳",
   "lon": 123.18,
   "lat": 41.27,
   "type": "city",
   "modern": "今辽宁辽阳市",
   "note": "辽东镇城，全辽枢纽，开原南屏",
   "_global_id": "liaoyang_cheng",
   "_other_scenes": [
    "haizhou",
    "shenyang",
    "tieling"
   ],
   "elev": 23
  },
  {
   "id": "shenyang",
   "name": "沈阳",
   "lon": 123.43,
   "lat": 41.8,
   "type": "city",
   "modern": "今辽宁沈阳市",
   "note": "辽东重镇，开原陷后成为后金兵锋所指",
   "_global_id": "shenyang_cheng",
   "_other_scenes": [
    "fushun",
    "guangning",
    "haizhou",
    "liaoyang",
    "tieling"
   ],
   "elev": 50
  },
  {
   "id": "sarhu",
   "name": "萨尔浒",
   "lon": 124.12,
   "lat": 41.88,
   "type": "battlefield",
   "modern": "今抚顺大伙房水库一带",
   "note": "万历四十七年二月明金决战地；开铁之战为其后效",
   "_global_id": "sarhu",
   "_other_scenes": [
    "sarhu",
    "tieling"
   ],
   "elev": 135
  },
  {
   "id": "yehe",
   "name": "叶赫",
   "lon": 124.62,
   "lat": 43.15,
   "type": "city",
   "modern": "今吉林梨树叶赫镇",
   "note": "海西女真叶赫部（北关），开原北屏障；开原陷后一月被灭",
   "_global_id": "yehe",
   "_other_scenes": [
    "sarhu"
   ],
   "elev": 333
  },
  {
   "id": "hetu_ala",
   "name": "赫图阿拉",
   "lon": 125.09,
   "lat": 41.73,
   "type": "capital",
   "modern": "今辽宁新宾老城",
   "note": "后金都城（兴京），努尔哈赤起家之地",
   "_global_id": "hetuala",
   "_other_scenes": [
    "fushun",
    "liaoyang",
    "sarhu",
    "shenyang",
    "tieling",
    "yehe"
   ],
   "elev": 416
  },
  {
   "id": "fushun",
   "name": "抚顺",
   "lon": 123.9,
   "lat": 41.86,
   "type": "city",
   "modern": "今辽宁抚顺市",
   "note": "万历四十六年（1618）后金首破之明边堡，开原之前奏",
   "_global_id": "fushun",
   "_other_scenes": [
    "liaoyang",
    "shenyang",
    "tieling"
   ],
   "elev": 44
  },
  {
   "id": "hada",
   "name": "哈达部",
   "lon": 124.95,
   "lat": 42.62,
   "type": "tribe",
   "modern": "今辽宁开原东北、西丰一带",
   "note": "海西女真(扈伦)四部之一；于广顺关(南关市)与明互市，明藉南关羁縻哈达以牵制北关叶赫",
   "elev": 334
  }
 ],
 "persons": [
  {
   "id": "fengyuan",
   "name": "冯瑗",
   "role": "开原兵备道右参政",
   "side": "ming",
   "note": "（1572–1627）纂《开原图说》，实地调查辽北23城与女真分布，明人记当地事",
   "influence": 0
  },
  {
   "id": "malin",
   "name": "马林",
   "role": "援辽总兵",
   "side": "ming",
   "note": "开铁之战中死守开原，城破殉国",
   "influence": 1,
   "_global_id": "malin",
   "_other_scenes": [
    "sarhu"
   ]
  },
  {
   "id": "zhengzhifan",
   "name": "郑之范",
   "role": "开原兵备道（推官代守）",
   "side": "ming",
   "note": "以推官（掌刑狱）身份代守开原，明方记载称其贪懦弃城而逃、丢失官印",
   "influence": 2
  },
  {
   "id": "nurhaci",
   "name": "努尔哈赤",
   "role": "后金大汗",
   "side": "jin",
   "note": "万历四十七年率军克开原、铁岭，时年六十一",
   "influence": 0,
   "_global_id": "nuerhaci",
   "_other_scenes": [
    "fushun",
    "fuzhou",
    "gaizhou",
    "guangning",
    "haizhou",
    "jinzhouwei",
    "liaoyang",
    "ningyuan"
   ]
  },
  {
   "id": "xiongtinbi",
   "name": "熊廷弼",
   "role": "辽东经略",
   "side": "ming",
   "note": "开原陷后受命经略辽东，奏称『开原，河东根柢也』",
   "influence": 1,
   "_global_id": "xiongtingbing",
   "_other_scenes": [
    "guangning",
    "tieling"
   ]
  },
  {
   "id": "gaozhen",
   "name": "高贞",
   "role": "参将",
   "side": "ming",
   "note": "开原城破时殉国",
   "influence": 0
  },
  {
   "id": "yuhualong",
   "name": "于化龙",
   "role": "副将",
   "side": "ming",
   "note": "开原城破时殉国",
   "influence": 0
  },
  {
   "id": "liangong",
   "name": "何懋官",
   "role": "守备",
   "side": "ming",
   "note": "开原城破时殉国",
   "influence": 0
  },
  {
   "id": "jianghongli",
   "name": "姜弘立",
   "role": "朝鲜五道都元帅",
   "side": "chaoxian",
   "note": "（1560–1627）萨尔浒之战率约1.3万朝鲜兵隶东路刘綎助明；阿布达里岗后通款后金而降，明神宗未责反赐敕",
   "influence": 2,
   "_global_id": "jianghongli",
   "_other_scenes": [
    "sarhu",
    "shenyang"
   ]
  }
 ],
 "assertions": [
  {
   "id": "K001",
   "subject": "place:kaiyuan_cheng",
   "predicate": "建置",
   "value_text": "洪武二十一年(1388)于开元城设三万卫；『开元』避太祖讳改『开原』",
   "value": 1388,
   "source": "kaiyuan_tushuo",
   "layer": "record",
   "era": "洪武二十一年",
   "place": "kaiyuan_cheng",
   "confidence": 0.88,
   "quote_status": "paraphrase_unverified",
   "quote": "冯瑗《开原图说》：开原即元之黄龙府，山阻东南，河抱西北，扣、清二水环绕城面。",
   "note": "开元改开原因避朱元璋『元』字讳，为明代避讳史实例。",
   "_party": "明·开原兵备道",
   "_faction": null
  },
  {
   "id": "K002",
   "subject": "place:anle_zhou",
   "predicate": "性质",
   "value_text": "明代辽东仅设安乐、自在二州，专为安置内附女真等族",
   "value": 1409,
   "source": "kaiyuan_tushuo",
   "layer": "record",
   "era": "永乐七年",
   "place": "anle_zhou",
   "confidence": 0.85,
   "quote_status": "paraphrase_unverified",
   "quote": "永乐七年于开原城置安乐州、自在州，辽东仅有的两个州。",
   "note": "二州不属府县制，是明代辽东卫所制下特设的羁縻管理构件。",
   "_party": "明·开原兵备道",
   "_faction": null
  },
  {
   "id": "K003",
   "subject": "place:kaiyuan_mashi",
   "predicate": "功能",
   "value_text": "三关三市（广顺关南关市、镇北关北关市、新安关鞑靼马市），提督马市公署驻此",
   "value": 1430,
   "source": "wiki",
   "layer": "record",
   "era": "宣德正统间",
   "place": "kaiyuan_mashi",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "开原设三关三市，提督马市公署设在开原城，为辽东贸易中心。",
   "note": "互市是开原作为『东北亚丝绸之路丝关』的核心职能。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K004",
   "subject": "place:kaiyuan_mashi",
   "predicate": "产业",
   "value_text": "开原马市兴盛，使三万卫成为全国三大冶铁中心之一",
   "value": null,
   "source": "wiki",
   "layer": "record",
   "era": "明中期",
   "place": "kaiyuan_mashi",
   "confidence": 0.7,
   "quote_status": "paraphrase_unverified",
   "quote": "兴旺的马市贸易，使得开原三万卫成了全国三大冶铁中心之一。",
   "note": "冶铁能力支撑了边堡兵器与农具自给，是开原军镇的经济底座。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K005",
   "subject": "place:kaiyuan_cheng",
   "predicate": "战略地位",
   "value_text": "九边之端；西遏蒙古、北控海西、东逼建州、南屏辽沈",
   "value": null,
   "source": "wiki",
   "layer": "record",
   "era": "明",
   "place": "kaiyuan_cheng",
   "confidence": 0.85,
   "quote_status": "paraphrase_unverified",
   "quote": "开原，控临绝徼，翼带镇城，居全辽之上游，为东陲之险塞，九边危地此其最乎。",
   "note": "开原位于明辽东防御体系最北端，是明联络女真、蒙古的枢纽。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K006",
   "subject": "doc:kaiyuan_tushuo",
   "predicate": "史料价值",
   "value_text": "辽东镇唯一军事地理专著，明人记当地事，图说体例",
   "value": 1618,
   "source": "kaiyuan_tushuo",
   "layer": "record",
   "era": "万历四十六年",
   "place": "kaiyuan_cheng",
   "confidence": 0.9,
   "quote_status": "paraphrase_unverified",
   "quote": "《开原图说》上卷为开原各城堡图说，下卷为夷虏枝派图考及兵营图说。",
   "note": "以当时人记当地事，自明末以来被治东北史者视为权威。",
   "_party": "明·开原兵备道",
   "_faction": null
  },
  {
   "id": "K007",
   "subject": "doc:kaiyuan_tushuo",
   "predicate": "存佚",
   "value_text": "刻本稀少，钞本存华东师大/北师大/上图/复旦；台湾《玄览堂丛书》影印",
   "value": null,
   "source": "modern",
   "layer": "scholarship",
   "era": "今",
   "place": "kaiyuan_cheng",
   "confidence": 0.75,
   "quote_status": "paraphrase_unverified",
   "quote": "《开原图说》鲜有刊本，仅见兵部刊本、台湾中正图书馆刊本、玄览堂丛书刊本等。",
   "note": "原书属善本，数字化与开放获取是后续可做的众包缺口。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K008",
   "subject": "event:kaifa",
   "predicate": "出兵日",
   "value_text": "万历四十七年六月初十（公历 1619-07-20，锚点见 K024）努尔哈赤率军出静安堡",
   "value": 16190720,
   "source": "ming_shenzong_shilu",
   "layer": "record",
   "era": "万历四十七年六月",
   "place": "kaiyuan_cheng",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "万历四十七年六月初十，努尔哈赤率四万大军往攻开原，走三日后因雨驻扎。",
   "note": "公历锚点已由 K024 闭环（维基『开铁之战』条目：1619-07-20 / 07-26；区间 6 天与农历吻合）。",
   "_party": "明廷官方",
   "_faction": null
  },
  {
   "id": "K009",
   "subject": "event:kaifa",
   "predicate": "陷落日",
   "value_text": "万历四十七年六月十六（1619-07-26）克开原",
   "value": 16190726,
   "source": "ming_shenzong_shilu",
   "layer": "record",
   "era": "万历四十七年六月",
   "place": "kaiyuan_cheng",
   "confidence": 0.82,
   "quote_status": "paraphrase_unverified",
   "quote": "六月十六日直抵开原城下；叶赫报信，郑之范不信反鞭来使；后金分兵架梯，东南门失守。",
   "note": "出兵日与陷落日须区分：『六月初十』是出兵，『六月十六』是陷落。",
   "_party": "明廷官方",
   "_faction": null
  },
  {
   "id": "K010",
   "subject": "army:jin_kaifa",
   "predicate": "兵力",
   "value_text": "后金攻开原兵约四万",
   "value": 40000,
   "source": "mingshi",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.7,
   "quote_status": "paraphrase_unverified",
   "quote": "努尔哈赤率四万大军攻开原。",
   "note": "明方记载后金兵力，常含夸大成分，宜与清方对勘。",
   "_party": "清修·明臣",
   "_faction": null
  },
  {
   "id": "K011",
   "subject": "army:jin_kaifa",
   "predicate": "兵力",
   "value_text": "另有记载称后金『万骑』（约一万）从静安堡入",
   "value": 10000,
   "source": "wiki",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.45,
   "quote_status": "paraphrase_unverified",
   "quote": "万历四十七年六月，后金兵万骑从静安堡入，乘开原疏于防守之机一举而下。",
   "note": "与『四万』说相差四倍，属典型兵力记载分歧；需更多原始记载定夺。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K012",
   "subject": "person:malin",
   "predicate": "结局",
   "value_text": "总兵马林城破殉国",
   "value": null,
   "source": "mingshi",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.85,
   "quote_status": "paraphrase_unverified",
   "quote": "马林及副将于化龙、参将高贞、守备何懋官等明将尽数被杀。",
   "note": "与萨尔浒西路杜松同为主将殉国，明方叙事中『死事』典型。",
   "_party": "清修·明臣",
   "_faction": null
  },
  {
   "id": "K013",
   "subject": "person:zhengzhifan",
   "predicate": "评价",
   "value_text": "以推官代守，明方载其贪懦弃城、丢失官印",
   "value": null,
   "source": "mingshi",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.6,
   "quote_status": "paraphrase_unverified",
   "quote": "郑之范素贪，竟不发给草料，一日饿死二百余匹马；见势弃城逃跑，连官印都丢了。",
   "note": "明方叙事惯性地将失城归咎代守文官，宜谨慎对待。",
   "_party": "清修·明臣",
   "_faction": null
  },
  {
   "id": "K014",
   "subject": "person:zhengzhifan",
   "predicate": "评价",
   "value_text": "现代考订：开原失陷系多重结构原因，不宜全归郑之范一人",
   "value": null,
   "source": "modern",
   "layer": "scholarship",
   "era": "今",
   "place": "kaiyuan_cheng",
   "confidence": 0.7,
   "quote_status": "paraphrase_unverified",
   "quote": "开原军马分散、城外兵力未能协同，叶赫无力策应，援兵不至；个人贪懦是因素之一而非全部。",
   "note": "与 K013 构成『记载 vs 现代考订』之争，不裁决只陈列。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K015",
   "subject": "event:kaifa",
   "predicate": "屠城",
   "value_text": "明方/综述载开原被屠『十余万，仅余千余』",
   "value": 100000,
   "source": "wiki",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.4,
   "quote_status": "paraphrase_unverified",
   "quote": "开原本有十几万人居住，经后金血洗竟只剩一千多人。",
   "note": "屠城数字出自后世综述，清方实录不载己方屠戮，数字待核（见 K025）。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K016",
   "subject": "person:xiongtinbi",
   "predicate": "论断",
   "value_text": "熊廷弼：『开原，河东根柢也』，视开原—辽沈—京师为连锁防线",
   "value": null,
   "source": "ming_shenzong_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.85,
   "quote_status": "paraphrase_unverified",
   "quote": "开原为河东根底，欲保河东而开原必不可弃。今开原破矣，清阳弃矣，庆云抢矣……",
   "note": "此奏揭示开原陷落的战略连锁效应，是判断战役意义的权威一手材料。",
   "_party": "明廷官方",
   "_faction": null
  },
  {
   "id": "K017",
   "subject": "event:yehe",
   "predicate": "结果",
   "value_text": "开原陷后一月，叶赫孤立被灭，女真诸部基本统一",
   "value": 1619,
   "source": "mingshi",
   "layer": "record",
   "era": "万历四十七年七月",
   "place": "yehe",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "开原破而北关不敢不顺……既无背腋之虞，又合东西之势以交攻，而辽沈何可守也。",
   "note": "印证『局部优势累积』：开原一落，后金在每一点都转为局部占优。",
   "_party": "清修·明臣",
   "_faction": null
  },
  {
   "id": "K018",
   "subject": "place:kaiyuan_cheng",
   "predicate": "地形",
   "value_text": "山阻东南、河抱西北，扣、清二水环绕城面",
   "value": null,
   "source": "kaiyuan_tushuo",
   "layer": "record",
   "era": "明",
   "place": "kaiyuan_cheng",
   "confidence": 0.82,
   "quote_status": "paraphrase_unverified",
   "quote": "瑗按开原城即辽之黄龙府，山阻东南，河抱西北，扣、清二水环绕城面。",
   "note": "与现有 ASTER 高程网格一致：开原处清河、辽河之间低地，东、北为丘陵。",
   "_party": "明·开原兵备道",
   "_faction": null
  },
  {
   "id": "K019",
   "subject": "event:kaifa",
   "predicate": "性质",
   "value_text": "萨尔浒之后后金顺势扩大战果的关键一战，非孤立事件",
   "value": null,
   "source": "modern",
   "layer": "scholarship",
   "era": "今",
   "place": "kaiyuan_cheng",
   "confidence": 0.78,
   "quote_status": "paraphrase_unverified",
   "quote": "开铁之战是萨尔浒之战后后金乘胜扩大战果、攻占辽东重镇的战役。",
   "note": "时间上紧接萨尔浒（二月），是同一战略节奏的延续。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K020",
   "subject": "event:kaifa",
   "predicate": "战术原则",
   "value_text": "印证局部优势：后金集中四万精骑，开原守军分散于城外堡寨、军马散漫，局部始终劣势",
   "value": null,
   "source": "modern",
   "layer": "scholarship",
   "era": "今",
   "place": "kaiyuan_cheng",
   "confidence": 0.72,
   "quote_status": "paraphrase_unverified",
   "quote": "开原守军防备松懈、城外士兵散驻、盔甲杂乱、军马分散，未能集中有效抵抗。",
   "note": "这是萨尔浒『以少胜多实为局部优势累积』原则在县级尺度的又一次体现。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K021",
   "subject": "place:kaiyuan_mashi",
   "predicate": "影响",
   "value_text": "马市促进女真/蒙古与中原物资交流，『和戎之利』",
   "value": null,
   "source": "wiki",
   "layer": "record",
   "era": "明",
   "place": "kaiyuan_mashi",
   "confidence": 0.75,
   "quote_status": "paraphrase_unverified",
   "quote": "马市方便了各民族之间的物资贸易，推动了经济发展与交融。",
   "note": "开原马市是明代边疆『互市—羁縻—制衡』政策的实物样本。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K022",
   "subject": "place:kaiyuan_cheng",
   "predicate": "建置·清",
   "value_text": "康熙三年(1664)设开原县，奉天府首批四县之一",
   "value": 1664,
   "source": "mingshi",
   "layer": "record",
   "era": "清康熙三年",
   "place": "kaiyuan_cheng",
   "confidence": 0.85,
   "quote_status": "paraphrase_unverified",
   "quote": "清康熙三年设开原县，为奉天府首批所建四县之一。",
   "note": "清承明卫所制后改州县制，开原由军镇转为民县。",
   "_party": "清修·明臣",
   "_faction": null
  },
  {
   "id": "K023",
   "subject": "river:liaohe",
   "predicate": "水文",
   "value_text": "开原西临辽河，清河、寇河、柴河贯境，共166条河流",
   "value": null,
   "source": "wiki",
   "layer": "record",
   "era": "今",
   "place": "kaiyuan_cheng",
   "confidence": 0.7,
   "quote_status": "paraphrase_unverified",
   "quote": "开原境内有河流166条，主要河流有辽河、清河、寇河、柴河等。",
   "note": "水网是开原军镇补给与防御的命脉，也是后金雨季行军的天候变量。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K024",
   "subject": "event:kaifa",
   "predicate": "公历锚点",
   "value_text": "出兵 1619-07-20；陷落 1619-07-26（区间 6 天，农历六月初十/十六换算）",
   "value": null,
   "source": "wiki",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.85,
   "quote_status": "paraphrase_unverified",
   "quote": "万历四十七年六月初十（1619年7月20日）努尔哈赤亲起四万大军往攻开原；六月十六（7月26日）直抵开原城下。",
   "note": "农历→公历换算依维基『开铁之战』条目（wbjc.net / profilpelajar.com 等转载）；lunardate / borax 库均只覆盖 1900–2100，本地不可独立核验，故升为 record 但仍标 paraphrase_unverified。区间 6 天与史料六月初十→十六自洽。",
   "_party": "二手综述",
   "_faction": null
  },
  {
   "id": "K025",
   "subject": "event:kaifa",
   "predicate": "屠城数字",
   "value_text": "缺口：屠城『十余万』仅见明方/综述，清方实录不载，数字待第三方核对",
   "value": null,
   "source": "qing_taizu_shilu",
   "layer": "gap",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.0,
   "quote_status": "paraphrase_unverified",
   "quote": "",
   "note": "胜方史料几乎不记己方屠戮，此数字本质是『对方叙事』，须标注其来源偏向。",
   "lead": {
    "where": "《明神宗实录》万历四十七年萨尔浒后叙功/勘状卷；《清太祖实录》天命四年对应月卷(查其是否回避);朝鲜《李朝实录》光海君日记(若闻辽东屠戮);地方志《开原县志》光绪/宣统本「兵燹」门。",
    "skills": [
     "古文",
     "统计",
     "朝语"
    ],
    "accept": "给出「十余万」说法的最早出处与引用链条, 并对照清方是否回避; 若数字本身不可考, 给出可信区间与原因, 并明确标注这是「对方叙事」而非中立计数。",
    "effort": "2-3 周"
   },
   "_party": "清修官史",
   "_faction": null
  },
  {
   "id": "K026",
   "subject": "event:sarhu",
   "predicate": "朝鲜参战",
   "value_text": "朝鲜应明征出兵：以姜弘立为五道都元帅、金景瑞副，率约1.3万兵编入东路刘綎军，萨尔浒非明单方之战",
   "value": null,
   "source": "chaoxian_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "sarhu",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "光海君以姜弘立为五道都元帅，金景瑞副之，率兵一万三千助明，隶刘綎东路。",
   "note": "朝鲜为明盟国，萨尔浒东路实含朝鲜军，故三方史料中朝鲜非旁观；原始见《光海君日记》(朝鲜实录)。",
   "_party": "朝鲜官方",
   "_faction": null
  },
  {
   "id": "K026a",
   "subject": "person:jianghongli",
   "predicate": "处境",
   "value_text": "姜弘立受光海君密旨通款后金，表出兵非本愿(为报壬辰援朝之恩)；阿布达里岗刘綎败后令中右营结阵观望，左营金应河力战阵亡，旋遣通事洽降",
   "value": null,
   "source": "chaoxian_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "sarhu",
   "confidence": 0.78,
   "quote_status": "paraphrase_unverified",
   "quote": "姜弘立遣通事黄连海诣后金，言朝鲜出兵迫于明命非其本意；副帅金景瑞单骑见代善，约『两国无怨，各解兵』。",
   "note": "朝鲜军降后金，明监军乔一琦坠崖死；此为朝鲜实录详载，是三方叙事中朝鲜立场核心。",
   "_party": "朝鲜官方",
   "_faction": null
  },
  {
   "id": "K026b",
   "subject": "person:jianghongli",
   "predicate": "明廷反应",
   "value_text": "明神宗未责朝鲜不战而降，反遣敕使赐敕书、赏银万两，仍望朝鲜牵制后金",
   "value": null,
   "source": "chaoxian_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "sarhu",
   "confidence": 0.75,
   "quote_status": "paraphrase_unverified",
   "quote": "万历帝赐敕：『朕抚有万邦，绥玆属国，既安危之相倚……勉图后效，毋弃前功，雪耻除凶，务期殄灭。』",
   "note": "明对萨尔浒之降极度宽容，因战略仍需朝鲜为左腋之患牵制后金。",
   "_party": "朝鲜官方",
   "_faction": null
  },
  {
   "id": "K026c",
   "subject": "event:kaifa",
   "predicate": "朝鲜处境",
   "value_text": "熊廷弼奏：开原未破时『朝鲜未败，犹有左腋之患』；开原破则朝鲜失牵制后金之凭，『不敢不从』后金",
   "value": null,
   "source": "ming_shenzong_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.82,
   "quote_status": "paraphrase_unverified",
   "quote": "贼未破开原时……朝鲜未败，犹有左腋之患。今开原破而北关不敢不顺，使币往来，而朝鲜不敢不从。",
   "note": "此奏载明实录，将开原陷落与朝鲜战略处境直接锁合，是三方共振关键环节；朝鲜侧见 K026a/b。",
   "_party": "明廷官方",
   "_faction": null
  },
  {
   "id": "K026d",
   "subject": "event:kaifa",
   "predicate": "朝鲜记载",
   "value_text": "朝鲜实录记开原、铁岭连陷，努尔哈赤威迫日甚；光海君处两难，终与后金往来(即明方所谓『不敢不从』)",
   "value": null,
   "source": "chaoxian_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.6,
   "quote_status": "paraphrase_unverified",
   "quote": "开原、铁岭相继陷没，虏势益张，我国介于其间，进退维谷。",
   "note": "朝鲜实录原文待核，此条据《光海君日记》转引综述；三方史料(明/清/朝鲜)至此均对开原陷落有记载，原 K026 缺口收窄。",
   "_party": "朝鲜官方",
   "_faction": null
  },
  {
   "id": "K027a",
   "subject": "place:kaiyuan_mashi",
   "predicate": "互市—海西",
   "value_text": "开原三关三市中，北关市(镇北关)通海西叶赫部、南关市(广顺关)通海西哈达部，是明羁縻海西女真主渠道",
   "value": null,
   "source": "kaiyuan_tushuo",
   "layer": "record",
   "era": "明",
   "place": "kaiyuan_mashi",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "开原马市北关通叶赫、南关通哈达，明藉互市羁縻海西，以夷制夷。",
   "note": "互市—羁縻—制衡，是明经营海西的核心手段。",
   "_party": "明·开原兵备道",
   "_faction": null
  },
  {
   "id": "K027b",
   "subject": "place:yehe",
   "predicate": "海西四部",
   "value_text": "海西女真(扈伦四部)为叶赫、哈达、乌拉、辉发；开原北面屏障，明以互市+结盟制衡之",
   "value": null,
   "source": "modern",
   "layer": "scholarship",
   "era": "明",
   "place": "yehe",
   "confidence": 0.78,
   "quote_status": "paraphrase_unverified",
   "quote": "海西四部叶赫、哈达、乌拉、辉发，错居开原东北，明联之以扦北虏、制建州。",
   "note": "乌拉、辉发二部未在地图标节点(超出辽东核心地形视野)，以四部整体记。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K027c",
   "subject": "place:hada",
   "predicate": "互市",
   "value_text": "哈达部于广顺关(南关市)与明互市，明藉南关羁縻哈达以牵制北关叶赫",
   "value": null,
   "source": "kaiyuan_tushuo",
   "layer": "record",
   "era": "明",
   "place": "hada",
   "confidence": 0.75,
   "quote_status": "paraphrase_unverified",
   "quote": "南关之市通哈达，明因以离北关而弱叶赫。",
   "note": "南关(哈达)—北关(叶赫)的互市格局，是明『以夷制夷』的实物样本。",
   "_party": "明·开原兵备道",
   "_faction": null
  },
  {
   "id": "K027d",
   "subject": "event:kaifa",
   "predicate": "海西—开原屏障",
   "value_text": "开原未陷时海西叶赫为开原北屏(熊廷弼『北关相倚，犹有后背之忧』)；后金先服叶赫再破开原，抽掉明辽东北面屏障",
   "value": null,
   "source": "ming_shenzong_shilu",
   "layer": "record",
   "era": "万历四十七年",
   "place": "kaiyuan_cheng",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "北关(叶赫)相倚，犹有后背之忧；开原破而北关不敢不顺。",
   "note": "与 K017『开原陷后叶赫灭』呼应，海西屏障的抽离是开原失守的结构性前提。",
   "_party": "明廷官方",
   "_faction": null
  },
  {
   "id": "K027e",
   "subject": "place:yehe",
   "predicate": "统一海西",
   "value_text": "万历四十七年八月努尔哈赤灭叶赫，海西四部基本并入后金，开原北面再无缓冲",
   "value": 1619,
   "source": "mingshi",
   "layer": "record",
   "era": "万历四十七年八月",
   "place": "yehe",
   "confidence": 0.8,
   "quote_status": "paraphrase_unverified",
   "quote": "八月，努尔哈赤灭叶赫，海西诸部悉平。",
   "note": "统一海西使后金南面再无牵制，遂得专意辽沈。",
   "_party": "清修·明臣",
   "_faction": null
  },
  {
   "id": "K028a",
   "subject": "dist:kaiyuan_cheng:tieling",
   "predicate": "明制里",
   "value_text": "开原→铁岭 约 57 里（直线 32.7 km）",
   "value": 57,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何模型，明制里 = km / 0.576；直线非实际行程（沿辽河谷/驿路绕行更远）。与史料『开原铁岭相距一日程』吻合（明制一日军行 ~30–40 里）。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028b",
   "subject": "dist:kaiyuan_cheng:liaoyang",
   "predicate": "明制里",
   "value_text": "开原→辽阳 约 275 里（直线 158.1 km）",
   "value": 275,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；开原→辽阳为辽东都司北南主轴，与熊廷弼『辽阳、开原、京师不可分割』的防线判断一致。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028c",
   "subject": "dist:kaiyuan_cheng:shenyang",
   "predicate": "明制里",
   "value_text": "开原→沈阳 约 167 里（直线 96.4 km）",
   "value": 167,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；沈阳卫为开原南向最近的重镇。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028d",
   "subject": "dist:kaiyuan_cheng:fushun",
   "predicate": "明制里",
   "value_text": "开原→抚顺 约 128 里（直线 73.7 km）",
   "value": 128,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；抚顺所 1618 已先陷（K018 地形视野），开原陷后辽沈侧翼尽失。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028e",
   "subject": "dist:kaiyuan_cheng:yehe",
   "predicate": "明制里",
   "value_text": "开原→叶赫 约 126 里（直线 72.8 km）",
   "value": 126,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；叶赫为开原最近的海西部落，与『开原北关相倚』互为犄角。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028f",
   "subject": "dist:kaiyuan_cheng:hetu_ala",
   "predicate": "明制里",
   "value_text": "开原→赫图阿拉 约 217 里（直线 124.9 km）",
   "value": 217,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；与 route_kaiyuan（努尔哈赤进军开原）共用同一对坐标，验证一致性。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028g",
   "subject": "dist:kaiyuan_cheng:sarhu",
   "predicate": "明制里",
   "value_text": "开原→萨尔浒 约 124 里（直线 71.3 km）",
   "value": 124,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；萨尔浒之战主战场，开原为北路马林部出发地。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K028h",
   "subject": "dist:kaiyuan_cheng:kaiyuan_mashi",
   "predicate": "明制里",
   "value_text": "开原→开原马市 约 5 里（直线 2.8 km）",
   "value": 5,
   "source": "modern",
   "layer": "inference",
   "era": "当下",
   "place": "kaiyuan_cheng",
   "confidence": 0.95,
   "quote_status": "generated",
   "quote": "",
   "note": "haversine 几何；马市紧邻开原城外，与『在城北门外』史载一致。",
   "_party": "学界",
   "_faction": null
  },
  {
   "id": "K029",
   "subject": "event:kaifa",
   "predicate": "地方志记载",
   "value_text": "缺口：《开原县志·万历四十六年东夷入犯》条尚未录入——该志为清末纂修的地方志，记万历四十六年（1619 陷落前一年）后金已入犯开原境，是理解次年速陷的关键前史",
   "value": null,
   "source": "xuantong_kao",
   "layer": "gap",
   "era": "万历四十六年",
   "place": "kaiyuan_cheng",
   "confidence": 0.0,
   "quote_status": "paraphrase_unverified",
   "quote": "",
   "note": "此源已在 sources.json 登记但无任何断言引用它。与其编一条来源可疑的记载来充数，不如把『登记了但没读到原文』本身作为缺口挂出来——这正是本项目把缺口当一等公民的用法。",
   "lead": {
    "where": "《开原县志》(宣统纂修, 清末)「万历四十六年东夷入犯」条; 《中国地方志联合目录》查馆藏(辽宁省图书馆/中科院文献情报中心); 辽海丛书影印本若已收。",
    "skills": [
     "方志学",
     "古文"
    ],
    "accept": "录入该条原文(影印或点校), 注明藏本与卷页; 评估其对「次年速陷」解释力的增量——即 1618 已入犯、1619 才正式破城之间的时间差意味着什么。",
    "effort": "1-2 周"
   },
   "_party": "清·地方志",
   "_faction": null
  }
 ],
 "conflicts": [
  {
   "id": "cf:army:jin_kaifa|兵力",
   "subject": "army:jin_kaifa",
   "predicate": "兵力",
   "kind": "record_vs_record",
   "count": 2,
   "spread": 4.0,
   "assertion_ids": [
    "K010",
    "K011"
   ]
  }
 ],
 "gaps": [
  "K025",
  "K029"
 ],
 "events": [
  {
   "id": "ev_sanwan",
   "year": 1388,
   "era": "洪武二十一年",
   "kind": "建置",
   "title": "设三万卫",
   "place": "kaiyuan_cheng",
   "text": "平定北元太尉纳哈出后，于开元城设三万卫；『开元』避太祖讳改『开原』。"
  },
  {
   "id": "ev_kaiyuanwei",
   "year": 1392,
   "era": "洪武二十五年",
   "kind": "建置",
   "title": "置开原卫",
   "place": "sanwan_wei",
   "text": "设开原卫（开元中护卫），开元城正式改称开原城。"
  },
  {
   "id": "ev_anle",
   "year": 1409,
   "era": "永乐七年",
   "kind": "建置",
   "title": "置安乐州、自在州",
   "place": "anle_zhou",
   "text": "于开原城置安乐州、自在州，安置内附女真等族；此为明代辽东仅有的两个州。"
  },
  {
   "id": "ev_mashi",
   "year": 1430,
   "era": "宣德正统间",
   "kind": "互市",
   "title": "开原马市成规模",
   "place": "kaiyuan_mashi",
   "text": "开原设三关三市（广顺关南关市、镇北关北关市、新安关鞑靼马市），提督马市公署驻此，辽东贸易中心。"
  },
  {
   "id": "ev_tushuo",
   "year": 1618,
   "era": "万历四十六年",
   "kind": "著述",
   "title": "《开原图说》成书",
   "place": "kaiyuan_cheng",
   "text": "开原兵备道冯瑗实地调查后纂成军事地理专著，详记辽北23城与女真四国枝派；书中已录『万历四十六年东夷入犯尅去』。"
  },
  {
   "id": "ev_sarhu",
   "year": 1619,
   "era": "万历四十七年二月",
   "kind": "战事",
   "title": "萨尔浒之战",
   "place": "sarhu",
   "text": "后金大破明四路大军。开原明军退守，为开铁之战的直接前因。",
   "subject": "event:sarhu"
  },
  {
   "id": "ev_kaifa",
   "year": 1619,
   "era": "万历四十七年六月",
   "kind": "战事",
   "title": "开铁之战",
   "place": "kaiyuan_cheng",
   "text": "六月初十努尔哈赤率军出静安堡，六月十六（7月26日）克开原；七月克铁岭。明总兵马林等殉国，郑之范弃城。",
   "subject": "event:kaifa"
  },
  {
   "id": "ev_yehe",
   "year": 1619,
   "era": "万历四十七年七月",
   "kind": "战事",
   "title": "叶赫灭亡",
   "place": "yehe",
   "text": "开原既陷，叶赫失去明方倚仗，孤立无援，一个月后被后金攻灭收编，女真诸部基本统一。",
   "subject": "event:yehe"
  },
  {
   "id": "ev_xianzhi",
   "year": 1664,
   "era": "清康熙三年",
   "kind": "建置",
   "title": "设开原县",
   "place": "kaiyuan_cheng",
   "text": "清初设开原县，为奉天府首批所建四县之一；柳条边盛京边墙自开原北经过。"
  },
  {
   "id": "ev_shi",
   "year": 1989,
   "era": "1989",
   "kind": "建置",
   "title": "撤县设市",
   "place": "kaiyuan_cheng",
   "text": "开原撤县设县级市，由铁岭市代管。"
  }
 ],
 "edges": [
  {
   "from": "kaiyuan_mashi",
   "to": "guangshun",
   "type": "mashi",
   "label": "广顺关·南关市（哈达/建州）"
  },
  {
   "from": "kaiyuan_mashi",
   "to": "zhenbei",
   "type": "mashi",
   "label": "镇北关·北关市（叶赫/海西）"
  },
  {
   "from": "kaiyuan_mashi",
   "to": "xinan",
   "type": "mashi",
   "label": "新安关·鞑靼马市（蒙古）"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "sanwan_wei",
   "type": "admin",
   "label": "三万卫治"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "liaohai_wei",
   "type": "admin",
   "label": "辽海卫治"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "anle_zhou",
   "type": "admin",
   "label": "安乐州治"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "fushun",
   "type": "mil",
   "label": "萨尔浒前奏：抚顺先陷（1618）"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "sarhu",
   "type": "mil",
   "label": "萨尔浒后明军退守开原"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "yehe",
   "type": "mil",
   "label": "北屏叶赫（开原陷则叶赫孤）"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "tieling",
   "type": "mil",
   "label": "西路援铁岭"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "liaoyang",
   "type": "mil",
   "label": "南屏辽阳"
  },
  {
   "from": "kaiyuan_cheng",
   "to": "shenyang",
   "type": "mil",
   "label": "进取辽沈之跳板"
  },
  {
   "from": "guangshun",
   "to": "hada",
   "type": "mashi",
   "label": "广顺关·南关市·通海西哈达部"
  },
  {
   "from": "zhenbei",
   "to": "yehe",
   "type": "mashi",
   "label": "镇北关·北关市·通海西叶赫部"
  },
  {
   "from": "yehe",
   "to": "hada",
   "type": "tribe",
   "label": "海西(扈伦)四部·叶赫—哈达同盟"
  },
  {
   "from": "hetu_ala",
   "to": "kaiyuan_cheng",
   "type": "mil",
   "label": "后金自赫图阿拉北攻开原"
  }
 ],
 "route": {
  "id": "route_kaiyuan",
  "name": "赫图阿拉→开原（努尔哈赤 开原之战进军）",
  "nodes": [
   {
    "place": "hetu_ala",
    "at": "1619-07-20"
   },
   {
    "place": "kaiyuan_cheng",
    "at": "1619-07-26"
   }
  ]
 },
 "route_report": {
  "route": "route_kaiyuan",
  "legs": [
   {
    "km": 124.9,
    "li": 217,
    "hours": 58.66,
    "days": 7.33,
    "ascent_m": 814,
    "descent_m": 1142,
    "max_slope_pct": 5.5,
    "elev_start": 416,
    "elev_end": 88,
    "elev_max": 648,
    "profile": [
     416,
     402,
     370,
     345,
     359,
     383,
     411,
     444,
     525,
     591,
     625,
     626,
     641,
     648,
     631,
     596,
     556,
     531,
     527,
     529,
     512,
     498,
     488,
     478,
     436,
     403,
     383,
     376,
     340,
     291,
     252,
     222,
     251,
     317,
     385,
     430,
     430,
     439,
     465,
     485,
     474,
     482,
     513,
     569,
     535,
     469,
     430,
     418,
     391,
     346,
     305,
     275,
     279,
     285,
     282,
     243,
     211,
     184,
     162,
     145,
     202,
     242,
     254,
     237,
     239,
     257,
     261,
     250,
     244,
     232,
     229,
     238,
     219,
     198,
     184,
     170,
     164,
     155,
     139,
     117,
     99,
     97,
     94,
     93,
     88
    ],
    "from": "hetu_ala",
    "to": "kaiyuan_cheng",
    "from_at": "1619-07-20",
    "to_at": "1619-07-26",
    "reported_days": 6,
    "strain": 1.22
   }
  ],
  "total_km": 124.9,
  "total_li": 217,
  "total_ascent_m": 814,
  "model_days": 7.33,
  "reported_days": 6,
  "strain": 1.22,
  "flat_equiv_days": 7.38,
  "strain_label": "基本吻合"
 },
 "route_verdict": "开原路地形紧张度 1.22（基本吻合），明显低于萨尔浒后金主力路 2.64（明显紧张，强烈建议复查（路线/分批/夜行？））。说明努尔哈赤攻开原为一次相对常规的强行军，萨尔浒才是超常速闪击——与\"局部优势 = 速度 × 距离累积\"的判断一致。"
};
