# -*- coding: utf-8 -*-
"""为历史模拟器生成 Natural Earth 矢量底图 + 辽东边墙。

v0.55 引入。目标：让 demo/sim_engine.html 的底图与 demo/sarhu.html
视觉一致（羊皮纸底+山影+蓝色河流+省界+边墙），而不是裸露的绿黄棕色块。

输出：demo/sim_basemap.js（window.SIM_BASEMAP，自包含 file:// 可用）。

策略：复借 tools/ingestion/basemap.py 的 _clip_all/clip_layer/
Sutherland-Hodgman 裁剪（已经处理「跨 bbox 的大陆多边形」），按两个
bbox 各裁一套并叠加辽东边墙。坐标精度统一压到 3 位小数（~100m），
控制切片体积。
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "ingestion"))
import basemap as BM  # noqa: E402  复借：clip_layer / _clip_all / _decimate_geom

ROOT = os.path.dirname(HERE)

# 两套视野：
#  战区：萨尔浒 + 辽东全境（西至山海关/宁远、东至赫图阿拉/吉林），南至
#  旅顺/金州，约 119.5–129.0°E / 38.5–44.5°N；
#  全中国：完整中华大地（73–136°E / 18–54°N），与 SD.basemap 的中国裁剪一致。
LIAODONG_BBOX = (119.5, 38.5, 129.0, 44.5)
CHINA_BBOX = (73.5, 18.0, 135.1, 53.6)


def _round_floats(obj, nd=3):
    """递归把所有 float 压到 nd 位小数（用于边墙 path 已是 [[lon,lat],...] 的情形）。"""
    if isinstance(obj, (int,)):
        return obj
    if isinstance(obj, float):
        return round(obj, nd)
    if isinstance(obj, list):
        return [_round_floats(x, nd) for x in obj]
    if isinstance(obj, dict):
        return {k: _round_floats(v, nd) for k, v in obj.items()}
    return obj


def _load_wall():
    """辽东边墙（壳级共享，已存在 data/geo/liaodong_wall.json）。"""
    p = os.path.join(ROOT, "data", "geo", "liaodong_wall.json")
    if not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as f:
        w = json.load(f)
    w["path"] = _round_floats(w.get("path", []), nd=3)
    return w


def _load_liaodong_rivers():
    """辽东骨干补充水系（浑河/苏子河）。

    NE 1:50m 在辽东 bbox 内仅含 辽河/西拉木伦河/西辽河，缺 浑河/苏子河 两条
    明—清战役定义性骨干水系（萨尔浒 1619 战场核心在抚顺—新宾—赫图阿拉一线，
    即 浑河/苏子河 河谷）。本文件由 v0.222b 创建，坐标约 5–10km 精度，
    带 approx+note 诚实标注。复用 county/sarhu 页面的同一份共享资产，保证
    战棋沙盘与 county/sarhu 底图水网一致。
    """
    p = os.path.join(ROOT, "data", "geo", "liaodong_rivers.json")
    if not os.path.exists(p):
        return []
    with open(p, encoding="utf-8") as f:
        d = json.load(f)
    return d.get("rivers", [])


def _build_one(bbox, with_admin1, nd=3, stride=2):
    """裁一个 bbox 的 NE 矢量底图（陆/海/省界/河/湖/海岸线）。"""
    emb = BM._clip_all(bbox, nd=nd, stride=stride, with_admin1=with_admin1)
    emb["_bbox"] = [round(x, 3) for x in bbox]
    return emb


def _correct_land(bbox, nd=3):
    """v0.232 O4 修正：陆地多边形单独以 stride=2 裁剪。

    根因：_clip_all 对 land 也按 stride 抽稀；stride>=3 会把欧亚大陆海岸线
    这种**高密度闭合多边形**抽稀成自交/退化环，导致大陆主体消失、'land'
    退化为若干岛屿碎块→海岸掩膜反相（海变陆、陆变海）。county 壳底图用
    stride=2 故正确。此处 land 强制 stride=2（与 county 同源），其余图层
    仍按原 stride 控体积。land 仅用于海岸掩膜（战棋底图用 DemTopo 影像，
    不靠 land 填色），stride=2 体积可接受。
    """
    return BM._clip_all(bbox, nd=nd, stride=2, with_admin1=False)["land"]


def main():
    # 战区：视野小，要 admin1 细节，精度保留 3 位
    liaodong = _build_one(LIAODONG_BBOX, with_admin1=True, nd=3, stride=2)
    # 合并辽东骨干补充水系（浑河/苏子河），与 county/sarhu 页面同源、诚实约记
    liaodong_rivers = _load_liaodong_rivers()
    if liaodong_rivers:
        BM._merge_extra_rivers(liaodong, liaodong_rivers, LIAODONG_BBOX, nd=3)
    # 全中国：与 SD.basemap 同样的精度/抽稀，避免重复体积（国家视图不画辽河支流）
    china = _build_one(CHINA_BBOX, with_admin1=True, nd=2, stride=3)
    # v0.232 O4：land 强制 stride=2（stride>=3 会把大陆海岸线多边形抽稀成退化环→掩膜反相）
    liaodong["land"] = _correct_land(LIAODONG_BBOX, nd=3)
    china["land"] = _correct_land(CHINA_BBOX, nd=2)
    wall = _load_wall()

    out = {
        "meta": {
            "source": "Natural Earth 1:50m (公共领域) + 辽东边墙 (data/geo/liaodong_wall.json)",
            "views": {
                "liaodong": {"bbox": list(LIAODONG_BBOX), "nd": 3, "stride": 2},
                "china":    {"bbox": list(CHINA_BBOX),    "nd": 2, "stride": 3},
            },
            "wall_view": "liaodong-only（边墙仅在战区视图显示；全中国视角留空）",
        },
        "liaodong": liaodong,
        "china": china,
        "wall": wall,
    }

    dst = os.path.join(ROOT, "demo", "sim_basemap.js")
    payload = json.dumps(out, ensure_ascii=False, separators=(",", ":"))
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/gen_sim_basemap.py — Natural Earth 矢量底图 + 辽东边墙\n")
        f.write("// file:// 可用（已注入，勿手改）。羊皮纸 + 山影地图见 demo/sim_engine.html\n")
        f.write("window.SIM_BASEMAP = " + payload + ";\n")
    print("OK:", dst, "size=", os.path.getsize(dst), "bytes")
    for view in ("liaodong", "china"):
        d = out[view]
        print("  %-9s land=%d admin1=%d rivers=%d lakes=%d coastline=%d bbox=%s" % (
            view, len(d.get("land", [])), len(d.get("admin1", [])),
            len(d.get("rivers", [])), len(d.get("lakes", [])),
            len(d.get("coastline", [])), d.get("_bbox")))


if __name__ == "__main__":
    main()
