#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 demo/china_terrain.js —— 把中国全域真实高程网格
(data/terrain/china_coarse_grid.json, ASTER GDEM v3 实测米) 编译成
file:// 可直接 <script> 加载的全局变量 window.CHINA_TERRAIN。

设计要点（对应需求"地图就用中国地形图，只需根据海拔对地图颜色渲染"）：
- 数据是真实高程（非示意），来源 ASTER GDEM v3，OpenTopoData 采样。
- 编译为内联 JS 全局，避免 file:// 下 fetch 被浏览器禁用的坑。
- 渲染端（sim_engine.html）按海拔分层设色（hypsometric），此脚本只负责搬运数据。

与 gen_sim_bundle.py 同范：数据只由本脚本生成，禁止手改产物。
重跑即可刷新（例如未来换了更高精度的网格）。
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "terrain", "china_coarse_grid.json")
OUT = os.path.join(ROOT, "demo", "china_terrain.js")


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        d = json.load(f)

    # 校验结构完整性
    nx, ny = d["nx"], d["ny"]
    assert len(d["elev"]) == nx * ny, f"elev 长度 {len(d['elev'])} != {nx}x{ny}"
    # 高程取整（原值多为整数，取整省体积且渲染无影响）
    elev = [int(v) if v is not None else None for v in d["elev"]]

    payload = {
        "lon0": d["lon0"],
        "lat0": d["lat0"],
        "step": d["step"],
        "nx": nx,
        "ny": ny,
        "unit": d.get("unit", "meter"),
        "min": d.get("min"),
        "max": d.get("max"),
        "elev": elev,
    }
    js = (
        "// AUTO-GENERATED by tools/gen_china_terrain.py — 禁止手改，重跑脚本刷新。\n"
        "// 来源: ASTER GDEM v3 (NASA/METI), OpenTopoData 公共实例采样；真实实测高程(米)。\n"
        "// 用途: 历史模拟器底图（按海拔分层设色）。\n"
        "window.CHINA_TERRAIN = "
        + json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
        + ";\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"wrote {OUT}  ({len(js)} bytes, grid {nx}x{ny}, water+land ready)")


if __name__ == "__main__":
    main()
